-- Seed generated from /Users/saifalikhan/Desktop/sustainly-green/Categories  subcat.xlsx
-- Date: 2026-06-27
-- Notes: Source spreadsheet does not map subcategories to parent categories.
--        Subcategories are attached to an imported holding category for later remapping.

begin;

-- Categories
insert into public.categories (name, slug, active, sort_order, raw_firebase)
values
  ('Baby, Kids & Family', 'baby-kids-family', true, 1, $json${"source":"categories_subcat_xlsx","imported_at":"2026-06-27"}$json$::jsonb),
  ('Water & Waste Waster System', 'water-waste-waster-system', true, 2, $json${"source":"categories_subcat_xlsx","imported_at":"2026-06-27"}$json$::jsonb),
  ('Eco-Friendly Home & Lifestyle Products', 'eco-friendly-home-lifestyle-products', true, 3, $json${"source":"categories_subcat_xlsx","imported_at":"2026-06-27"}$json$::jsonb),
  ('Sustainable Textiles & Apparel', 'sustainable-textiles-apparel', true, 4, $json${"source":"categories_subcat_xlsx","imported_at":"2026-06-27"}$json$::jsonb),
  ('Circular Economy & Recycling Services', 'circular-economy-recycling-services', true, 5, $json${"source":"categories_subcat_xlsx","imported_at":"2026-06-27"}$json$::jsonb),
  ('ESG, Certification & Advisory Services', 'esg-certification-advisory-services', true, 6, $json${"source":"categories_subcat_xlsx","imported_at":"2026-06-27"}$json$::jsonb),
  ('Eco Tourism & Travel', 'eco-tourism-travel', true, 7, $json${"source":"categories_subcat_xlsx","imported_at":"2026-06-27"}$json$::jsonb),
  ('Green Mobility & Transport Systems', 'green-mobility-transport-systems', true, 8, $json${"source":"categories_subcat_xlsx","imported_at":"2026-06-27"}$json$::jsonb),
  ('Sustainable Logistics & Supply Chain Services', 'sustainable-logistics-supply-chain-services', true, 9, $json${"source":"categories_subcat_xlsx","imported_at":"2026-06-27"}$json$::jsonb),
  ('Sustainable Packaging Materials', 'sustainable-packaging-materials', true, 10, $json${"source":"categories_subcat_xlsx","imported_at":"2026-06-27"}$json$::jsonb),
  ('Green Build & Materials', 'green-build-materials', true, 11, $json${"source":"categories_subcat_xlsx","imported_at":"2026-06-27"}$json$::jsonb),
  ('Natural & Organic Personal Care Products', 'natural-organic-personal-care-products', true, 12, $json${"source":"categories_subcat_xlsx","imported_at":"2026-06-27"}$json$::jsonb),
  ('Organic Food & Agri Products', 'organic-food-agri-products', true, 13, $json${"source":"categories_subcat_xlsx","imported_at":"2026-06-27"}$json$::jsonb),
  ('Renewable Energy & Efficiency Technologies', 'renewable-energy-efficiency-technologies', true, 14, $json${"source":"categories_subcat_xlsx","imported_at":"2026-06-27"}$json$::jsonb),
  ('Environmental Solutions', 'environmental-solutions', true, 15, $json${"source":"categories_subcat_xlsx","imported_at":"2026-06-27"}$json$::jsonb),
  ('Imported Subcategories (Unmapped)', 'imported-subcategories-unmapped', true, 16, $json${"source":"categories_subcat_xlsx","purpose":"holding_category_for_unmapped_subcategories","imported_at":"2026-06-27"}$json$::jsonb)
on conflict (slug) do update set name = excluded.name, active = true, sort_order = excluded.sort_order, updated_at = now();

-- Subcategories: attached to imported holding category because parent mapping is not present in source file.
with parent as (select id from public.categories where slug = 'imported-subcategories-unmapped' limit 1),
source_subcategories(name, sort_order) as (
  values
    ('Paper & Cardboard Packaging', 1),
    ('Bioenzyme / compost accelerators', 2),
    ('Balers, Shredders, Crushers (basic recycling machinery)', 3),
    ('Carbon-neutral freight forwarding', 4),
    ('Renewable Product Compliance', 5),
    ('Bamboo / Sustainable Wood', 6),
    ('Solid & Hazardous Waste Management', 7),
    ('Water & Air Testing', 8),
    ('Solar-powered warehousing', 9),
    ('Air Quality Testing', 10),
    ('Waste Collection & Logistics', 11),
    ('Environmental Monitoring & Sensors', 12),
    ('Packaging Raw Materials (bio-resins, pulp, corrugated sheets)', 13),
    ('Soaps & Hygiene', 14),
    ('Vegan Leather Products', 15),
    ('Organic Skincare', 16),
    ('Environmental Monitoring', 17),
    ('Organic Haircare', 18),
    ('EV Charger Testing & Certification', 19),
    ('Environmental Compliance & Audits', 20),
    ('Emission Monitoring & CEMS', 21),
    ('Composters (home & commercial)', 22),
    ('Solar Inverters', 23),
    ('Reusable Straws & Cutlery Sets (metal/bamboo + carry pouches)', 24),
    ('Energy Audit', 25),
    ('Eco Toys & Learning', 26),
    ('Industrial/B2B Packaging (pallet wraps, bulk packs)', 27),
    ('Reusable Water Bottles & Flasks (steel/glass)', 28),
    ('Eco-friendly Activewear', 29),
    ('Waste Bins (segregation bins)', 30),
    ('Solar & Storage Certification', 31),
    ('Sustainable packaging logistics', 32),
    ('Compliance Monitoring & Testing', 33),
    ('Environmental Testing', 34),
    ('Battery Recycling', 35),
    ('EV fleet leasing & rental', 36),
    ('Organic Waste & Composting', 37),
    ('E-Cycles', 38),
    ('Renewable Equipment Testing', 39),
    ('Solar Batteries / Storage', 40),
    ('Eco Household Essentials (cleaning, kitchen, storage)', 41),
    ('Sustainable School Essentials', 42),
    ('Product Testing Labs', 43),
    ('Green Building Certifications', 44),
    ('Sustainable Clothing', 45),
    ('ESG & Sustainability Reporting', 46),
    ('Irrigation Systems (drip, sprinkler)', 47),
    ('Reusable Coffee Cups & Tumblers (travel mugs)', 48),
    ('Paper & Cardboard Alternatives (paper tape, paper mailers, paper cups)', 49),
    ('Ethical Fashion Brands', 50),
    ('Third-Party Testing Labs', 51),
    ('Recycling Raw Materials (recycled plastic pellets, paper pulp)', 52),
    ('Batteries', 53),
    ('Maintenance Services', 54),
    ('Renewable Testing & Certification', 55),
    ('Eco Bricks / AAC Blocks', 56),
    ('Plastic-Free Grocery & Produce Bags (mesh/cotton, bulk bags)', 57),
    ('Industrial Dust & Fume Extraction', 58),
    ('Personal Care Eco Products (bamboo toothbrush, eco razors)', 59),
    ('Energy Storage & Backup', 60),
    ('Compostable Packaging (bags, films, mailers)', 61),
    ('Compostable Tableware (plates, cups, bowls, cutlery)', 62),
    ('Family Wellness', 63),
    ('Hemp Clothing & Textiles', 64),
    ('Water Filters & Purifiers', 65),
    ('GHG Verification', 66),
    ('Compliance Testing Labs', 67),
    ('Kids Furniture & Home', 68),
    ('RO / UV Systems', 69),
    ('Recycled Steel & Metals', 70),
    ('Solar Installation', 71),
    ('Low-VOC Paints & Coatings', 72),
    ('Water Quality Testing', 73),
    ('Sustainable Footwear', 74),
    ('Essential Oils & Aromatherapy', 75),
    ('Reverse logistics & EPR', 76),
    ('Testing, Inspection & Lab Reports', 77),
    ('Organic Snacks & Processed Foods', 78),
    ('Sustainable Agriculture Certifications', 79),
    ('EV Charger Installations', 80),
    ('Industrial Waste', 81),
    ('Solar Mounting Structures', 82),
    ('Food Storage & Wraps (silicone bags, beeswax wraps, jar covers)', 83),
    ('Carbon Footprint', 84),
    ('Storage Tanks & Accessories (eco materials)', 85),
    ('ISO certifications', 86),
    ('Flooring (bamboo, reclaimed wood)', 87),
    ('Enviro Testing Labs', 88),
    ('Solar Water Heaters', 89),
    ('Organic Baby Care', 90),
    ('Insulation (natural fiber, recycled)', 91),
    ('Eco-Labeling', 92),
    ('Organic Baby Clothing', 93),
    ('organic baby food', 94),
    ('Rainwater Harvesting Kits', 95),
    ('Reusable Baby Essentials', 96),
    ('Solar Cables & Connectors', 97),
    ('Green cold chain', 98),
    ('Sustainable Bags & Accessories', 99),
    ('E-Bike Batteries & Battery Packs', 100),
    ('Plastic Scrap & PET Waste', 101),
    ('Lunch Boxes & Meal Prep Containers (steel/glass/silicone)', 102),
    ('Baby Bedding & Comfort', 103),
    ('Energy Ratings', 104),
    ('AGM / VRLA Sealed Batteries', 105),
    ('Sustainable Feeding Products', 106),
    ('Eco-Friendly Diapers', 107),
    ('Organic Fruits & Vegetables', 108),
    ('Bamboo Fabric Clothing', 109),
    ('toddler care products', 110),
    ('Reusable Packaging Systems (returnable containers)', 111),
    ('Organic Tea/Coffee & Drinks', 112),
    ('Water-Saving Fixtures (taps, aerators, low-flow showers)', 113),
    ('Heavy-Duty E-Bikes', 114),
    ('EPR Compliance Services', 115),
    ('Solar, EV & Battery Testing', 116),
    ('Noise Pollution Control', 117),
    ('Environmental Claims Verification', 118),
    ('Air Pollution Control Systems', 119),
    ('Organic Rice, Grains & Pulses', 120),
    ('Energy Tech Testing & Certification', 121),
    ('Wastewater Treatment (ETP / STP)', 122),
    ('EV last-mile delivery', 123),
    ('Cargo E-Bikes', 124),
    ('Indoor Air Quality (IAQ) Solutions', 125),
    ('Charging Infrastructure & Stations', 126),
    ('Clean Energy Testing Labs', 127),
    ('Organic Spices & Herbs', 128),
    ('Organic Cotton Apparel', 129),
    ('Folding E-Bikes', 130),
    ('Natural Sweeteners & Oils (honey, cold-pressed oils)', 131),
    ('Emission & Air Monitoring', 132),
    ('Solar Lights (street, garden, home)', 133),
    ('IAQ & Environmental Testing', 134),
    ('Plastic-Free Kids Products', 135),
    ('Solar & EV Compliance Testing', 136),
    ('Water, Air & Emissions Testing', 137),
    ('Organic Certifications', 138),
    ('Biogas Units (small-scale)', 139),
    ('Commuter E-Bikes', 140),
    ('Recycled Polyester Clothing', 141),
    ('organic newborn products', 142),
    ('Eco Certificate', 143),
    ('E-Waste Recycling', 144),
    ('Compostable Trash Bags & Bin Liners', 145),
    ('Safety Testing Labs', 146),
    ('Battery Installations', 147),
    ('Climate, Carbon & ESG Advisory.', 148),
    ('Solar/Battery/EV Testing', 149),
    ('Natural Certifications', 150),
    ('Solar Panels & Modules', 151)
)
insert into public.subcategories (category_id, name, active, sort_order, raw_firebase)
select parent.id, source_subcategories.name, true, source_subcategories.sort_order, $json${"source":"categories_subcat_xlsx","parent_mapping":"unmapped","imported_at":"2026-06-27"}$json$::jsonb
from source_subcategories cross join parent
where not exists (
  select 1 from public.subcategories existing
  where existing.category_id = parent.id and lower(existing.name) = lower(source_subcategories.name)
);

-- Certification standards
with source_certifications(name, sort_order) as (
  values
    ('ISO 9001', 1),
    ('ISO 14001', 2),
    ('ISO 45001', 3),
    ('ISO 50001', 4),
    ('ISO 22000', 5),
    ('FSSC 22000', 6),
    ('ISO/IEC 27001', 7),
    ('ISO 14064 (GHG) / ISO 14067 (CFP)', 8),
    ('NPOP Organic Certification', 9),
    ('EU Organic / USDA Organic', 10),
    ('ISCC PLUS / ISCC EU', 11),
    ('FSC', 12),
    ('Fairtrade', 13),
    ('Rainforest Alliance', 14),
    ('LEED', 15),
    ('EDGE', 16),
    ('IGBC Ratings', 17),
    ('GOTS', 18)
)
insert into public.certifications (name, status, raw_firebase)
select source_certifications.name, 'Active', $json${"source":"categories_subcat_xlsx","imported_at":"2026-06-27"}$json$::jsonb
from source_certifications
where not exists (select 1 from public.certifications existing where lower(existing.name) = lower(source_certifications.name));

-- Certification bodies
with source_bodies(name, sort_order) as (
  values
    ('DNV Business Assurance India Pvt. Ltd.', 1),
    ('TÜV SÜD South Asia Pvt. Ltd.', 2),
    ('TÜV India Pvt. Ltd. (TÜV NORD)', 3),
    ('TÜV Rheinland (India) Pvt. Ltd.', 4),
    ('Intertek India Pvt. Ltd.', 5),
    ('SGS India Pvt. Ltd.', 6),
    ('Bureau Veritas (India) Pvt. Ltd.', 7),
    ('IRCLASS Systems and Solutions Pvt. Ltd. (Indian Register Quality Systems)', 8),
    ('International Certifications Services Pvt. Ltd.', 9),
    ('BSCIC Certifications Pvt. Ltd.', 10),
    ('MTIC Intercert India Pvt. Ltd. (formerly TÜV Intercert Saar India Pvt. Ltd.)', 11),
    ('Zenith Quality Assessors Pvt. Ltd.', 12),
    ('ACM EMB Pvt. Ltd.', 13),
    ('UL India Pvt. Ltd.', 14),
    ('Deutsch Quality Systems (India) Pvt. Ltd.', 15),
    ('Quality Austria Central Asia Pvt. Ltd.', 16),
    ('URS Certification Ltd. (India)', 17),
    ('AGSI Certification Pvt. Ltd.', 18),
    ('Cotecna Inspection India Pvt. Ltd.', 19),
    ('Quest Certification (P) Ltd.', 20),
    ('Ecocert India Pvt. Ltd.', 21),
    ('Indian Organic Certification Agency (INDOCERT)', 22),
    ('Lacon Quality Certification Pvt. Ltd.', 23),
    ('Aditi Organic Certifications Pvt. Ltd.', 24),
    ('CU Inspections India Pvt. Ltd. (Control Union)', 25),
    ('Uttarakhand State Organic Certification Agency (USOCA)', 26),
    ('TUV Austria (India) Pvt. Ltd', 27)
)
insert into public.certifying_bodies (name, country, status, raw_firebase)
select source_bodies.name, 'India', 'Active', $json${"source":"categories_subcat_xlsx","imported_at":"2026-06-27"}$json$::jsonb
from source_bodies
where not exists (select 1 from public.certifying_bodies existing where lower(existing.name) = lower(source_bodies.name));

commit;
